// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 06.05.2026, 08:57:38
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/Users/Marat/Desktop/vivien/client/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Marat/Desktop/vivien/client/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Marat/Desktop/vivien/client/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Marat/Desktop/vivien/client/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Marat/Desktop/vivien/client/app/plugins/**/*.{js,ts,mjs}","C:/Users/Marat/Desktop/vivien/client/app/composables/**/*.{js,ts,mjs}","C:/Users/Marat/Desktop/vivien/client/app/utils/**/*.{js,ts,mjs}","C:/Users/Marat/Desktop/vivien/client/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Marat/Desktop/vivien/client/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Marat/Desktop/vivien/client/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Marat/Desktop/vivien/client/app/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;